"$schema" = 'https://starship.rs/config-schema.json'

palette = "custom"

right_format = """
$time\
$cmd_duration\
"""
add_newline = false

[cmd_duration]
min_time = 1000
format = "[󰔟 $duration](blue)"
disabled = false

[time]
use_12hr = true
time_format = "%I:%M %p "
format = "[$time](overlay2)"
disabled = false

[character]
success_symbol = "[❯](pink)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[directory]
truncation_length = 4
truncation_symbol = "…/"
style = "bold cyan"
read_only = " 󰌾 "
home_symbol = " "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Repos" = " "
".config" = " "

# Git entry
[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"
format = '(\([+$added]($added_style)/[-$deleted]($deleted_style)\)) '

[git_status]
ahead = '[ $count](bold green) '
conflicted = '[󱡂 ](bold red) '
untracked = '[ $count](bold yellow) '
staged = '[ $count](bold green) '
stashed = '[ $count](cyan) '
deleted = '[ $count](bold red) '
modified = '[ $count](bold yellow) '
behind = '[ $count](bold purple) '
renamed = '[󰬴 $count](bold blue) '
up_to_date = '[ ](bold green) '
diverged = '[ $ahead_count  $behind_count ](bold red) '
format = '([$all_status$ahead_behind]($style))'

[git_branch]
symbol = " "

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[palettes.custom]
black = "#222436"
gray = "#444a73"
dark = "#2d3f76"
blue = "#82aaff"
cyan = "#86e1fc"
teal = "#8bd5ca"
green = "#a6da95"
red = "#ff757f"
orange = "#f5a97f"
yellow = "#eed49f"
pink = "#fca7ea"
purple = "#c099ff"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
